### ISSUE TITLE
Reload BIN file

### ISSUE THREAD

**Issue by Veshialle** [ip2location/logstash-filter-ip2proxy#2]
I could not get if there is some sort of automatic reload after the change of the file or, to reload it, I need to restart entire logstash/pipeline.

Thanks
Bye

**Comment by ip2location** [comment]
May we know which command you use to start the Logstash?

**Comment by Veshialle** [comment]
I usually run as a daemon, and the command line inside service file is:
/usr/share/logstash/bin/logstash "--path.settings" "/etc/logstash"

If needed I can provide configurations above (logstash.yml).

This issue is not opened because I found that it doesnt reload after changes but to ask IF the BIN file is reloaded by the plugin after file change (as other filter do, like geoip).


Thanks

**Comment by ip2location** [comment]
You can use the command below for the automatic reload:
`bin/logstash -f test-pipeline.conf --config.reload.automatic`
