### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by sbacelic** [ip2location/logstash-filter-ip2proxy#4]
It seems like there might be a problem with the recent cache implementation, pipeline is failing on this line:

```    if value = Cache.find(event, ip, @ip2proxyfilter, @cache_size).get('ip2proxy')```

Here is the log snippet:

`[ERROR][logstash.javapipeline    ][intake] Pipeline worker error, the pipeline will be stopped {:pipeline_id=>"intake", :error=>"", :exception=>Java::JavaUtil::ConcurrentModificationException, :backtrace=>["java.base/java.util.IdentityHashMap.forEach(IdentityHashMap.java:1358)", "org.logstash.Rubyfier.deepMap(Rubyfier.java:91)", "org.logstash.Rubyfier.lambda$initConverters$8(Rubyfier.java:119)", "org.logstash.Rubyfier.deep(Rubyfier.java:73)", "org.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_get_field(JrubyEventExtLibrary.java:110)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_ip2proxy_minus_2_dot_1_dot_0.lib.logstash.filters.ip2proxy.RUBY$method$filter$0(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-ip2proxy-2.1.0/lib/logstash/filters/ip2proxy.rb:44)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:106)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140)", "org.jruby.ir.targets.InvokeSite.fail(InvokeSite.java:278)", "usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:106)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140)", "org.jruby.ir.targets.InvokeSite.fail(InvokeSite.java:278)", "usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$block$multi_filter$1(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:178)", "org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:148)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:106)", "org.jruby.runtime.Block.yield(Block.java:184)", "org.jruby.RubyArray.each(RubyArray.java:1820)", "usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$multi_filter$0(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:175)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:106)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.logstash.config.ir.compiler.FilterDelegatorExt.doMultiFilter(FilterDelegatorExt.java:127)", "org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multiFilter(AbstractFilterDelegatorExt.java:134)", "org.logstash.generated.CompiledDataset3.compute(Unknown Source)", "org.logstash.generated.CompiledDataset3.compute(Unknown Source)", "org.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.compute(CompiledPipeline.java:329)", "org.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.compute(CompiledPipeline.java:323)", "org.logstash.execution.WorkerLoop.run(WorkerLoop.java:87)", "java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)", "java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)", "java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)", "java.base/java.lang.reflect.Method.invoke(Method.java:566)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:441)", "org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:305)", "org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:32)", "usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$block$start_workers$5(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:295)", "org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:138)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52)", "org.jruby.runtime.Block.call(Block.java:139)", "org.jruby.RubyProc.call(RubyProc.java:318)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)", "java.base/java.lang.Thread.run(Thread.java:829)"], :thread=>"#<Thread:0x782d912f@/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:54 sleep>"}`

might be related to https://github.com/ip2location/logstash-filter-ip2location/issues/19

**Comment by ip2location** [comment]
Hi @sbacelic

We are not able to reproduce the issue from our testing. Can you show us your Logstash Configuration file?

**Comment by sbacelic** [comment]
Hi,
here is pipeline.yml
```
 - pipeline.id: intake
  queue.type: persisted
  path.config: "/etc/logstash/conf.d/intake"
  pipeline.workers: 1
```
and here is intake config
```
input {
  rabbitmq {
    ack => true
    host => "xx"
    port => 5671
    connect_retry_interval => 10
    prefetch_count => 10
    user => "x"
    password => "x"
    queue => "x"
    passive => true
    ssl => true
  }
  rabbitmq {
    ack => true
    host => "yy"
    port => 5671
    connect_retry_interval => 10
    prefetch_count => 10
    user => "x"
    password => "x"
    queue => "x"
    passive => true
    ssl => true
  }
  rabbitmq {
    ack => true
    host => "zz"
    port => 5671
    connect_retry_interval => 10
    prefetch_count => 10
    user => "x"
    password => "x"
    queue => "x"
    passive => true
    ssl => true
  }  
}

filter {
  ip2proxy {
    database => "/etc/logstash/IP2PROXY-IP-PROXYTYPE-COUNTRY.BIN"
    remove_field => ["[ip2proxy][region]", "[ip2proxy][city]", "[ip2proxy][country_long]", "[ip2proxy][isp]", "[ip2proxy][last_seen]", "[ip2proxy][usage_type]", "[ip2proxy][as]", "[ip2proxy][asn]", "[ip2proxy][domain]", "[ip2proxy][country_short]"]
    source => "ip"
  }
}

output {
    elasticsearch {
    hosts => ["localhost:9200"]
    ilm_enabled => false
    index => "yyy-%{+xxxx.ww}"
  }
}
```

**Comment by ip2location** [comment]
Can you try it again with the latest version 2.2.0?

**Comment by ip2location** [comment]
@sbacelic We have added the **use_cache** field into the settings. You can set `use_cache => false` in your Logstash config file.
